version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:80"
    networks:
      database: {}
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./config:/var/www/html/config
      - ./assets:/var/www/html/assets
      #- .:/var/www/html

    env_file: .docker/env/docker.env

networks:
  database:
    external: true