<?php

namespace ContainerAPxCKNb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BsChjkBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BsChjkB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BsChjkB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'googleAuthenticator' => ['privates', 'App\\Security\\GoogleAuthenticator', 'getGoogleAuthenticatorService', true],
        ], [
            'googleAuthenticator' => 'App\\Security\\GoogleAuthenticator',
        ]);
    }
}
